### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by ikkentim** [fusez/Map-Editor#1]
This is more of an answer to your question
`I don't know why the indentation looks so messed up on here, it looks just fine in pawno.`

It looks off because pawno's indentation size is 4 spaces and github's is 8 spaces. You could replace (by regular expression) all \t with four spaces in pawno if you'd like to fix this.

In general I advice not to use tabs in code. Most editors have options to automatically convert tabs to spaces. But pawno, being as simple as it is, does not have this option.

**Comment by simonseidel** [comment]
I read this answer years ago but just forgot to write you an answer.
Thanks for clearing it up dude
